stages:
  - validate
  - destroy
tags:
  - job30
#variables:
#  TF_ROOT: "terraform" # The folder where Terraform configuration resides
#  TF_BACKEND_CONFIG: "-backend-config=bucket=my-tf-state -backend-config=key=terraform/state -backend-config=region=us-east-1"

before_script:
  # Update package list and install necessary tools, including wget and sudo
    - apt-get update && apt-get install -y gnupg software-properties-common curl wget sudo
    # Download the HashiCorp GPG key manually and store it
    - wget -O /tmp/hashicorp-archive-keyring.gpg https://apt.releases.hashicorp.com/gpg
    # Import the GPG key into the system's keyring
    - gpg --dearmor /tmp/hashicorp-archive-keyring.gpg | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
    # Explicitly import the missing GPG key (AA16FCBCA621E701)
    - curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
    # Add the HashiCorp repository to the sources list
    - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
    # Update package list again to include HashiCorp packages
    - apt update
    # Install Terraform
    - apt-get install -y terraform

 

validate:
  stage: validate
  script:
     - terraform init -backend-config=address=${TF_ADDRESS} -backend-config=lock_address=${TF_ADDRESS}/lock -backend-config=unlock_address=${TF_ADDRESS}/lock -backend-config=username=${TF_USERNAME} -backend-config=password=${TF_PASSWORD} -backend-config=lock_method=POST -backend-config=unlock_method=DELETE -backend-config=retry_wait_min=5  
     - terraform plan -out=tf
     - terraform apply -auto-approve
  when: manual 
  only:
    - main
  
  before_script:
  # Update package list and install necessary tools, including wget and sudo
      - apt-get update && apt-get install -y gnupg software-properties-common curl wget sudo
      # Download the HashiCorp GPG key manually and store it
      - wget -O /tmp/hashicorp-archive-keyring.gpg https://apt.releases.hashicorp.com/gpg
      # Import the GPG key into the system's keyring
      - gpg --dearmor /tmp/hashicorp-archive-keyring.gpg | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
      # Explicitly import the missing GPG key (AA16FCBCA621E701)
      - curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
      # Add the HashiCorp repository to the sources list
      - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
      # Update package list again to include HashiCorp packages
      - apt update
      # Install Terraform
      - apt-get install -y terraform
destroy:
    stage: destroy
    tags:
     - job30  
    script:
       - terraform init -backend-config=address=${TF_ADDRESS} -backend-config=lock_address=${TF_ADDRESS}/lock -backend-config=unlock_address=${TF_ADDRESS}/lock -backend-config=username=${TF_USERNAME} -backend-config=password=${TF_PASSWORD} -backend-config=lock_method=POST -backend-config=unlock_method=DELETE -backend-config=retry_wait_min=5
       - terraform destroy -auto-approve 
    when: manual 
    only:
      - main
