stages:
  - validate
  - plan
  - apply

variables:
  TF_ROOT: "terraform" # The folder where Terraform configuration resides
  TF_BACKEND_CONFIG: "-backend-config=bucket=my-tf-state -backend-config=key=terraform/state -backend-config=region=us-east-1"

before_script:
  # Update package list and install necessary tools, including wget and sudo
    - apt-get update && apt-get install -y gnupg software-properties-common curl wget sudo
    # Download the HashiCorp GPG key manually and store it
    - wget -O /tmp/hashicorp-archive-keyring.gpg https://apt.releases.hashicorp.com/gpg
    # Import the GPG key into the system's keyring
    - gpg --dearmor /tmp/hashicorp-archive-keyring.gpg | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
    # Explicitly import the missing GPG key (AA16FCBCA621E701)
    - curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
    # Add the HashiCorp repository to the sources list
    - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
    # Update package list again to include HashiCorp packages
    - apt update
    # Install Terraform
    - apt-get install -y terraform

 # - curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor > /usr/share/keyrings/hashicorp-archive-keyring.gpg
 # - apt-get update && apt-get install -y terraform

validate:
  stage: validate
  script:
    - cd $TF_ROOT
    - terraform init $TF_BACKEND_CONFIG
    - terraform validate
  only:
    - merge_requests
    - main

plan:
  stage: plan
  script:
    - cd $TF_ROOT
    - terraform init $TF_BACKEND_CONFIG
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - $TF_ROOT/tfplan
  only:
    - merge_requests
    - main

apply:
  stage: apply
  script:
    - cd $TF_ROOT
    - terraform init $TF_BACKEND_CONFIG
    - terraform apply -auto-approve
  when: manual
  only:
    - main
